<?php

/**
 * @file
 * This is the main module file.
 */

//reference challonge API code
include_once('/opt/bitnami/apps/drupal/htdocs/includes/challonge.class.php');

/**
 * Ajax menu callback.
 */
function UpdateScoresForm_callback($ajax) {
    if ($ajax) {
        ctools_include('ajax');
        ctools_include('modal');

        $form_state = array(
            'ajax' => TRUE,
            'title' => t('MyModule Modal Form'),
        );

// Use ctools to generate ajax instructions for the browser to create
// a form in a modal popup.
        $output = ctools_modal_form_wrapper('UpdateScoresForm_form', $form_state);

// If the form has been submitted, there may be additional instructions
// such as dismissing the modal popup.
        if (!empty($form_state['ajax_commands'])) {
            $output = $form_state['ajax_commands'];
        }

// Return the ajax instructions to the browser via ajax_render().
        print ajax_render($output);
        drupal_exit();
    }
    else {
        return drupal_get_form('UpdateScoresForm_form');
    }
}

function UpdateScoresForm_displayBracket($js) {
    //pass this in as parameter
    $tourneyID = '556b81a9b0554';


    //define settings for modal window
    //todo: the id here needs to be referenced in the link
  //also this sizing should vary by the number of matches in the tourney.

    drupal_add_js(array(
        'ctools-use-modal' => array(
            'modalSize' => array(
                'type' => 'fixed',
                'width' => 250,
                'height' => 250,
            ),
        ),
    ), 'setting');

    //set title
    $title = t('Bracket');

    //generate iframe content for bracket
    $output = t("<iframe src='http://challonge.com/") . $tourneyID . t("/module' width='100%' height='300' frameborder='0' scrolling='auto' allowtransparency='true'></iframe>");


    if ($js) {
    ctools_modal_render($title, $output);
  }
  else {
    drupal_set_title($title);
    return $output;
  }
}

/**
 * An example page.
 */
function UpdateScoresForm_page() {
// Load the modal library and add the modal javascript.
    ctools_include('modal');
    ctools_modal_add_js();
    return _UpdateScoresForm_make_link('View Bracket');
}
/**
 * Helper function to make a link.
 */
function _UpdateScoresForm_make_link($link_text = '') {
// Set a default value if no text in supplied.
    if (empty($link_text)) {
        $link_text = 'Magical Modal';
    }

    return '

' . l($link_text, 'UpdateScoresForm/nojs', array('attributes' => array('class' => 'ctools-use-modal'))) . '
';
}

//create a block to wrap this form module
function UpdateScoresForm_block_info() {
    $blocks = array();

    $blocks['UpdateScoresBlock'] = array(
        'info' => t('Update Scores Block'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}
/**
 * Implements hook_block_view().
 */
function UpdateScoresForm_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'UpdateScoresBlock':
            $block['subject'] = t('Update Scores Form Block');
            $block['content'] = drupal_get_form('UpdateScoresForm_form');
            break;
    }
    return $block;
}
/**
 * Implements hook_help().
 */
function UpdateScoresForm_help($path, $arg) {

    if ($path == 'admin/help#UpdateScoresForm') {
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('The form module is used to report match scores for the matches open matches you are participating in.') . '</p>';
        return $output;
    }
}
/**
 * Implementation of hook_menu().
 */
function UpdateScoresForm_menu() {

    $items['UpdateScoresForm/form'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'page arguments'=>array('UpdateScoresForm_form'));

    $items['UpdateScoresForm/page'] = array(
        'page callback' => 'UpdateScoresForm_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['UpdateScoresForm/%ctools_js'] = array(
        ///'page callback' => 'UpdateScoresForm_callback',
        'page callback' => 'UpdateScoresForm_displayBracket',

        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function UpdateScoresForm_form($form, &$form_state) {
    $form = array();
//TODO: need the match info and fields to enter score for each team. This will be an overlay window (hopefully).

    $form['name']=array(
        '#type'=>'textfield',
        '#title'=>t('Enter Team Name'),
        '#description'=>t('Team Name Goes Here')
    );

    $form['new_link_text'] = array(
        '#type' => 'textfield',
        '#title' => t('Link text'),
    );


    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>t('Join Tournament!')
    );

    return $form;
}

/**
 * Drupal form submit handler.
 */
function UpdateScoresForm_form_submit($form, &$form_state){

// Generate the new link using the submitted text value.
            $link = _UpdateScoresForm_make_link($form_state['values']['new_link_text']);

// Tell the browser to close the modal.
            $form_state['ajax_commands'][] = ctools_modal_command_dismiss();

// Tell the browser to replace the old link with the new one.
            $form_state['ajax_commands'][] = ajax_command_replace('#magical-modal-link', $link);
        }

function UpdateScoresForm_form_validate($form, &$form_state) {

   // if ($form_state['values']['name'] = ""){
     //   form_set_error('name', t('Team Name is a required field.'));}

}