

<?php

/**
 * @file
 * This is the main module file.
 */
 
 //reference challonge API code
 include_once DRUPAL_ROOT . '/includes/challonge.class.php';
 
 
//create a block to wrap this form module
function jointournamentform_block_info() {
  $blocks = array();

  $blocks['JoinTourneyBlock'] = array(
    'info' => t('Join Tourney Block'), 
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function jointournamentform_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'JoinTourneyBlock':
      $block['subject'] = t('Join Tournament Form Block');
      $block['content'] = drupal_get_form('jointournamentform_form1');
    break;
  }
  return $block;
}

 /**
 * Implements hook_help().
 */

function jointournamentform_help($path, $arg) {

  if ($path == 'admin/help#jointournamentform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The form module is used to allow a team to join a tournament') . '</p>';
    return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function jointournamentform_menu() {
	$items['jointournamentform/form1'] = array(
			'type' => MENU_CALLBACK,
			'access arguments' => array('access content'),
			'page callback' => 'drupal_get_form',
			'page arguments'=>array('jointournamentform_form1'));

	return $items;
}

function jointournamentform_form1($form, &$form_state) {
	$form = array();

    $form['name']=array(
        '#type'=>'textfield',
        '#title'=>t('Enter awesome Team Name'),
        '#description'=>t('Team Name Goes Here'),
    );
		

	$form['submit']=array(
			'#type'=>'submit',
			'#value'=>t('Join Tournament!')
	);

	return $form;
}

function jointournamentform_form1_submit($form, &$form_state){

 try {

     dpm($form_state);

 	//set tournament_id from url get parameter // TODO: need a better way to keep this state
	$parameters = drupal_get_query_parameters();
	if(isset($parameters['tid']))
		{
		  $tournament_id = $parameters['tid'];
		}

     $teamName = $form_state['values']['name'];

     drupal_set_message($tournament_id . '--' . $teamName  .  '---' . $GLOBALS['user']->uid);


     //createTeamAndAddToTournament($tournament_id, $form_state['values']['name'], $GLOBALS['user']);

     //exception handler
 } catch (Exception $e) {
     _watchdog_log($e->getMessage());sd
 }

}
function jointournamentform_form1_validate($form, &$form_state) {

  if ($form_state['values']['name'] = ""){
    form_set_error('name', t('Team Name is a required field.'));}

}