
<?php

/**
 * @file
 * This is the main module file.
 */

//reference challonge API code
include_once DRUPAL_ROOT . '/includes/challonge.class.php';

/**
 * Implementation of hook_menu().
 */
function manage_teams_form_menu() {
    $items = array();

    $items['teams/manage'] = array( //this creates a URL that will call this form at "teams/manage"
        'title' => 'Join Tournament', //page title
        'description' => 'Create and Add teams to a Tourney.',
        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.
        'page arguments' => array('manage_teams_form_form'), //put the name of the form here
        'access callback' => TRUE
    );
    return

        $items;
}

function manage_teams_form_form($form, &$form_state) {

    $form = array();

    $form['Enter_Team'] = array(
        '#type' => 'fieldset',
        '#title' => t('Add Team to Tourney'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );

    $form['Enter_Team']['team_name'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'Create New Team:',
        '#size' => 20,
        '#maxlength' => 50,

    // '#required' => TRUE, //make this field required
    );

    $form['Enter_Team']['existing_team_name'] = array(
        '#type' => 'select',
        '#title' => t('Choose an existing Team:'),
        '#options' => getExistingTeamsByUser($GLOBALS['user']),
        '#empty_option'=> t('--Choose an Existing Team--'),
    );

    $form['Enter_Team']['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Enter Team'),
    );

    return $form;
}


function manage_teams_form_form_validate($form, &$form_state) {

    $teamValue = trim($form_state['values']['team_name']);
    if(empty($teamValue) && (empty($form_state['values']['existing_team_name'])))
    {
        form_set_error('team_name',t('You must either create a team or choose one to enter:'));
    }

}

function manage_teams_form_form_submit($form, &$form_state) {

    watchdog('submit debug:  ',$form_state['values']['team_name']);

    drupal_set_message('you should not be here');
    return;

    dpm($form_state);

    try {
        //set tournament_id from url get parameter // TODO: need a better way to keep this state
        $parameters = drupal_get_query_parameters();
        if (isset($parameters['tid'])) {
            $tournament_id = $parameters['tid'];
            }
        else{

            //TODO: message that TID is missing
            }

        if(!empty($form_state['values']['team_name'])) {
                //use new team if provided
                $teamName = $form_state['values']['team_name'];
                $createTeam = TRUE;
            }
        else
            {
                //otherwise use existing team
                $teamName = $form_state['values']['existing_team_name'];
                $createTeam = FALSE;
            }

        createTeamAndAddToTournament($tournament_id, $teamName, $GLOBALS['user'],$createTeam);

        }
    //exception handler
    catch (Exception $e) {
        _watchdog_log($e->getMessage());
        }


}
