
<?php

/**
 * @file
 * This is the main module file.
 */

//reference challonge API code
include_once DRUPAL_ROOT . '/includes/challonge.class.php';

/**
 * Implementation of hook_menu().
 */
function manage_teams_form_menu() {
    $items = array();

    $items['teams/manage'] = array( //this creates a URL that will call this form at "teams/manage"
        'title' => 'Manage Teams Form', //page title
        'description' => 'Create and Add teams to a Tourney.',
        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.
        'page arguments' => array('manage_teams_form'), //put the name of the form here
        'access callback' => TRUE
    );
    return

        $items;
}

function manage_teams_form_form($form, &$form_state) {

    $form['name'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'Team Name:',
        '#size' => 10,
        '#maxlength' => 50,
        '#required' => TRUE, //make this field required
    );


    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Add Team'),
    );

    return $form;
}


function manage_teams_form_validate($form, &$form_state) {
    if (($form_state['values']['name'] = "")){
        form_set_error('Team', t('Team Name is Required'));
    }
}

function form_example_form_submit($form, &$form_state) {

    //dpm($form_state);

    try {
        //set tournament_id from url get parameter // TODO: need a better way to keep this state
        $parameters = drupal_get_query_parameters();
        if (isset($parameters['tid'])) {
            $tournament_id = $parameters['tid'];
    }

    $teamName = $form_state['values']['name'];

    drupal_set_message($tournament_id . '--' . $teamName . '---' . $GLOBALS['user']->uid);


    //createTeamAndAddToTournament($tournament_id, $form_state['values']['name'], $GLOBALS['user']);

    }
    //exception handler
    catch (Exception $e) {
        _watchdog_log($e->getMessage());
    }


}
